version: '3'

services:
  rapidpro2pg:
    image: rapidpro2pg:latest
    container_name: rapidpro2pg
    environment:
      - POSTGRESQL_URL='postgres://postgres:postgrespass=@localhost:5432/rapidpro2pg'
      - RAPIDPRO_URL=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - RAPIDPRO_AUTH=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    network_mode: "host"
