version: '3.9'

services:
  rapidpro2pg:
    build: .
    container_name: rapidpro2pg
    environment:
      POSTGRESQL_URL: ${POSTGRESQL_URL}
      RAPIDPRO_URL: ${RAPIDPRO_URL}
      RAPIDPRO_AUTH: ${RAPIDPRO_AUTH}
    network_mode: "host"
    command: node /usr/app/bin/index.js
