version: '3'

services:
  rapidpro2pg:
    image: rapidpro2pg:latest
    container_name: rapidpro2pg
    environment:
      - POSTGRESQL_URL=***************************
      - RAPIDPRO_URL=***************************
      - RAPIDPRO_AUTH=***************************
    network_mode: "host"
