name: Build rapidpro2pg and run test cases

on: [push, pull_request]

jobs:
  test:
    name: Test rapidpro2pg
    runs-on: ubuntu-18.04
    env:
      INT_PG_PASS: postgrespass
      INT_PG_USER: postgres
      INT_PG_DB: rapidpro2pgtest
      INT_RP_PORT: 6594

    services:
      postgres:
        image: postgres:9.5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{ env.INT_PG_PASS }}
          POSTGRES_USER: ${{ env.INT_PG_USER }}
          POSTGRES_DB: ${{ env.INT_PG_DB }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
